spring:
  application:
    name: server1
server:
  port: 8081

msg1: this is service1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册中心地址
  instance:
    appname: config-client
    instance-id: localhost:8081
