spring:
  application:
    name: server2
server:
  port: 8082

msg2: this is service2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册中心地址
  instance:
    appname: config-client
    instance-id: localhost:8082
